### ISSUE TITLE
מכרז רגיל - בכל 10 שניות יש לפנות לפונקציה LeadingPropositionAndUser

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#15]
הפונקציה מקבלת את ה JSON הבא:
{
"UserIsDisabled":false, כרגע להתעלם
"UserNominalToLead":null,  לא רלוונטי
"UserTotalToLead":null, לא רלוונטי כרגע
"StatusId":"Going", סטאטוס מכרז משימה נפרדת
"UserLastPropositionTotal":634.000000, מחיר אחרון שלי משימה נפרדת
"UserLastPropositionTotalPerUnit":0, לא רלוונטי במכרז רגיל
"UserLastPropositionTotalWithoutBenefits":null, לא רלוונטי במכרז רגיל
"UserLastPropositionRank":null, משימה נפרדת יחד עם LeadingPropositions
"LeadingPropositions":null, 
"Total":634.000000, מחיר מוביל משימה נפרדת
"DisplayRank":false, יהיה רלוונטי בהמשך
"Time":38662, נפתחה משימה נפרדת
"EndTime":"", אם יש ערך יופיע במכרז שהסתיים 
"ManualProposition":false, לא רלוונטי
"IsWinning":true, סטאטוס שלי במכרז ANOTHER MISSION OPENED
"WinningInfo":"הצעתך מובילה", - ANOTHER MISSION OPENED
"BenefitType":null, לא רלוונטי למכרז רגיל
"MadeInIsrael":null לא רלוונטי למכרז רגיל, 
"LocalWork":null, לא רלוונטי למכרז רגיל
"TotalLocationBenefit":null, לא רלוונטי למכרז רגיל
"TotalMadeInIsrael":null, לא רלוונטי למכרז רגיל
"TotalLocationBenefitPerUnit":null, לא רלוונטי למכרז רגיל
"TotalMadeInIsraelPerUnit":null, לא רלוונטי למכרז רגיל
"NeedApprovalMessages":[], הודעות במהלך המכרז נפתחה משימה בנפרד
"ServerTime":"09:15:38" זמן מערכת משימה נפרדת
}
משימות יפתחו בהמשך

**Comment by assafmodi** [comment]
הוספתי SLICE חדש עבור הנושא : LpauSlice
וכם רדוסר בהתאמה
