### ISSUE TITLE
דף מכרז רגיל - אישור הודעות במהלך המכרז

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#18]
כאשר יש קריאה לפונקציה LeadingPropositionAndUser
חוזרת רשימה של הודעות שצריכות אישור מיידי - NeedApprovalMessages - ברשימה זו מקבלים טקסט של הודעה ו ID
אם יש אברים ברשימה זו יש  להציג את ההודעות בהודעה קופצת (ברקע עדין מעדכנים את המסך כל 10 שניות)
ברגע שהמשתמש מאשר את ההודעות בדיאלוג צריך לשלוח לשרת לפונקציה ApproveMessages מבנה JSON שיכיל את ה USERID ואת ה IDS של כל ההודעות שאושרו על ידי המשתמש

**Comment by assafmodi** [comment]
![image](https://user-images.githubusercontent.com/86707714/155883680-66a2e04c-696c-489e-b642-fec19084d4b7.png)

**Comment by assafmodi** [comment]
אוקיי כרגע אני שולח את המערך הבא:
![image](https://user-images.githubusercontent.com/86707714/156923061-9873c37e-ee74-4b5a-aa2b-455e2dea4aa7.png)

ברגע שנחבר את האוטנטיקציה נשלח נתוני אמת לגבי  userid
