### ISSUE TITLE
דף מכרז רגיל - הצגת הודעה מיוחדת למי שמוגדר בעל עדיפות נשים

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#2]
כאשר הערך של השדה IsFemaleOwner בקריאה לפונקציה שמביאה מידע בעליית דף המכרז הוא TRUE יש להציג בדואלוג ההודעות שנפתח בעת פתיחת דף המכרז את ההודעה:
"הנך זכאי להעדפה של עידוד נשים בעסקים ולכן על מנת להוביל עליך להציע הצעה זהה להצעה המובילה"

**Comment by KerenMe** [comment]
קריאה לפונקציה TenderAndCurrentPropositionLines

**Comment by assafmodi** [comment]
בוצע
