### ISSUE TITLE
מכרז רגיל עידכון סטאטוס כל 10 שניות - הצעה אחרונה שלי והחיווי על מיקומה

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#20]
כל 10 שניות נעשת קריאה לפונקציה LeadingPropositionAndUser
בה מתקבלים שלושה פרמטרים - UserLastPropositionTotal , IsWinning, WinningInfo
![image](https://user-images.githubusercontent.com/38718670/153825648-5f598c36-9afb-4768-9cb8-05243ae89e37.png)
את UserLastPropositionTotal אתה מציג אם אין שם ערך להציג את הסימן מינוב
אם IsWinning הוא TRUE אז הטקסט WinningInfo צריך להיות ירוק 
אם IsWinning הוא FALSE וטרם הצעת הצעה במכרז זה (UserLastPropositionTotal  הוא NULL) אז ה WinningInfo צריך להיות בשחור
אם IsWinning הוא FALSE וכבר הצעת הצעה במכרז זה (UserLastPropositionTotal  הוא לא NULL) אז ה WinningInfo צריך להיות באדום

**Comment by assafmodi** [comment]
![image](https://user-images.githubusercontent.com/86707714/155878422-1a2d8099-cb22-481c-bb29-1720727c1b03.png)

**Comment by assafmodi** [comment]
בוצע
