### ISSUE TITLE
בדיקת נכונות מחיר לפריט

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#26]
בעת הקלדת מספר בשדה מחיר לפריט או בעת לחיצה על הכפתורים פלוס ומינוס יש לבדוק ש:
1. המחיר שהוקלד אינו גדול מ MaxPrice (זהו משתנה שקיים ב TenderLineDto)
2. המחיר שהוקלד אינו קטן מ MinPrice (זהו משתנה שקיים ב TenderLineDto)
3. המחיר שהוכנס אינו בכפולות של מדרגת הירידה - ההודעה שצריכה לקפוץ במקרה זה היא:
"המחיר שהצעת '195' לא השתנה על פי מדרגת המחיר לפריט זה '10.00'. האם ברצונך לשנות את הצעתך למחיר החוקי הקרוב ביותר '190.00'?"

כאשר אחד מהחוקים שלמעלה לא מתקימים צריך להוציא הודעה שמיידעת את המשתמש על הבעיה הזו.

**Comment by assafmodi** [comment]
תיקון והוספות (נכתב על ידי קרן)
1. יש להוסיף בדיקה שהערך אינו קטן מאפס
2. את ההודעה - 'המחיר שהצעת '195' לא השתנה על פי מדרגת המחיר לפריט זה '10.00'. האם ברצונך לשנות את הצעתך למחיר החוקי הקרוב ביותר '190.00 - צריך לשנות ל  המחיר שהצעת '195' לא השתנה על פי מדרגת המחיר לפריט זה '10.00'. - אין צורך לשים לו שום ערך במקום הערך שהקליד אלא רק ליידע אותו שיש בעיה בערך שהקליד
רוב תודות

**Comment by assafmodi** [comment]
בגדול צריך רק להציג הערות ולא להגביל את הסכום המוקלד או שמועלה  ומורד עם החיצים?

**Comment by assafmodi** [comment]
בוצע

**Comment by assafmodi** [comment]
קרן -  לאחר שהמשתמש מקליד ערך לא חוקי יש להחזיר לערך הקודם שהוקלד
צריך שההודעה תקפוץ ב ONBLUR של השדה
