### ISSUE TITLE
דף מכרז רגיל הגשת הצעה

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#27]
בעת הגשת הצעה צריך לפנות לשרת עם  הכתובת ConfirmProposition
יש לשלוח JSON שיכיל את המידע:
1. userId
2. tenderId
3. לכל פריט במכרז יש לשלוח:
א. TenderLineId
ב. מחיר ליחידה

בקבלת תשובה מהשרת יש לפתוח את מסך אישור ההצעה. ראה באג נוסף על התשובה מהשרות והמסך של אישור ההצעה

**Comment by assafmodi** [comment]
בוצע הוכנה התשתית...ברגע שיוחלט איך להתקדם  נבצע

**Comment by KerenMe** [comment]
מבנה ה json שיש לשלוח הוא
{
userId: 1,
tenderId: 2,
lines: [
{
tenderLineId: 12,
price: 123.45
],
{
tenderLineId: 13,
price: 34.50
]
}
התשובה אותה תקבל מהשירות היא רשימה של lines כמו שיש לך ב DTO הראשי (TenderLineDto)
את הרשימה הזו אתה תעדכן בערכים:
Price
TotalWithoutBenefits
מייד לאחר קבלת התשובה צריך לפתוח את מסך אישור ההצעה
את המידע למסך זה צריך לקחת מ TenderDTo ו TenderLineDto
