### ISSUE TITLE
 (שאינו אני) דף מכרז רגיל - הצגת הודעה מיוחדת במכרזים בהם יש ספק בעל עדיפות נשים

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#3]
כאשר הערך בשדה HasUsersWithFemaleOwner בקריאה לפונקציה בעליית דף מכרז הוא TRUE והערך בשדה IsFemaleOwner הוא FALSE
עליך להציג בדיאלוג ההודעות שנפתח בעת פתיחת הדף את ההודעה:
"במכרז זה משתתף לפחות ספק אחד הזכאי להעדפה של עידוד נשים בעסקים."

**Comment by KerenMe** [comment]
קריאה לפונקציה TenderAndCurrentPropositionLines

**Comment by assafmodi** [comment]
בוצע

![image](https://user-images.githubusercontent.com/86707714/153018510-46329a79-1255-4965-92ed-d0f169fe47bb.png)
