### ISSUE TITLE
מסך אישור הצעה - הצגת שגיאות

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#31]
בעת קריאה לפונקציה ConfirmProposition ההצעה עוברת בדיקה של סט של חוקים בשרת
אם יש שגיאות מתקבלת השגיאה במבנה הבא:
Errors: [
"המחיר קטן מידי",
"המכרז הסתיים"
]
יש להציג הודעות אלה כהודעה אדומה (ראה הודעה אדומה בעיצובים של מטריקס).
בסגירת הודעות השגיאה יש לסגור את מסך אישור ההצעה ולחזור למסך של המכרז.

**Comment by assafmodi** [comment]
בעליית הדף....

**Comment by assafmodi** [comment]
הפונקציה מגיבה לשני המצבים גם למצב של isuue 27 וגם למצב ב issue 31
