### ISSUE TITLE
דף מכרז - פריטים שעודכנו

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#32]
כאשר משתמש משנה את המחיר ליחידה בשורה צריך להופיע חיווי "עודכן" על השורה.

**Comment by assafmodi** [comment]
בוצע
<img width="311" alt="image" src="https://user-images.githubusercontent.com/86707714/162612185-959bde46-497c-419a-896b-adc0b934b211.png">
