### ISSUE TITLE
דף מכרז - הצגת הודעות בכניסה למכרז

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#33]
בכניסה למכרז מוצג דיאלוג עם ההודעות הקבועות של המכרז
בדיאלוג זה יש להוסיף CHECKBOX "אל תציג זאת שוב"

יש לשמור נתון זה ברשימת המכרזים וכאשר פותחים את המכרז לשלוח את ה BOOL הזה לדף המכרז ובהתאם לערך שלו צריך להחליט האם לא להציג

**Comment by assafmodi** [comment]
1. הועבר לקרן לטיפול
