### ISSUE TITLE
דף מכרז - מכרז בסטאטוס ENDED או DECODED

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#34]
כאשר הסטאטוס הוא ENDED או DECODED יש להציג את המידע על הפריטים לתצוגה בלבד ללא אפשרות לפתוח את האקורדיון לשינוי המחיר

**Comment by assafmodi** [comment]
בוצע
 onClick={() => (status!=='Ended' && status!=='Decoded')? setExpand((expand) => !expand):null}
