### ISSUE TITLE
מכרז רגיל- הפניה מדף המכרז לרשימת המכרזים

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#37]
צריך להוסיף כפתור לדף המכרז שיחזיר את המשתמש לרשימת המכרזים.

**Comment by assafmodi** [comment]
איפה יישב הכפתור
מה המלל
הרקע

**Comment by assafmodi** [comment]
צריך להוסיף כפתור לדף המכרז שיחזיר את המשתמש לרשימת המכרזים.
איפה יישב הכפתור
מה המלל
הרקע

‫בתאריך יום א׳, 3 באפר׳ 2022 ב-11:07 מאת ‪KerenMe‬‏ <‪
***@***.***‬‏>:‬

**Comment by assafmodi** [comment]
בוצע
