### ISSUE TITLE
דף מכרז רגיל - הצגת סימן מטבע רלוונטי ליד שדות מחיר

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#4]
כאשר דף המכרז עולה בקריא הלפונקציה מגיע השדה - CurrencyId
בכל מקום בדף שיש שדה מטבע יש להציג את המטבע הנשלח בשדה זה

**Comment by KerenMe** [comment]
קריאה לפונקציה TenderAndCurrentPropositionLines

**Comment by assafmodi** [comment]
בוצע חשוב להדגיש שמכיוון שמבנה הנתונים אינו כולל ב LINES את הפרמטר  CurrencyId הוספתי אותו והוא מקבל את הערך מאובייקט האב
