### ISSUE TITLE
דף מכרז בדיקה בעת שינוי מחיר ליחידה בפריט

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#44]
עד עתה בעת שינוי המחיר לפריט היה צריך לבדוק שההפרש בין המחי הקודם למחיר הנוכחי הוא בכפולות של המדרגת יחידה
מעתה יש לבדוק רק שהמחיר שהוקלד יורד לפחות במדרגה אחת אך לא חייב לרדת בכפולות של מדרגה

לדוגמא אם מחיר ליחידה הוא 100 ומדרגת המחיר היא 5
אז אם אדם הקליד 95 זה תקין (כפולה אחת של המדרגת ירידה9
אם אדם הגיש 97 זה לא תקין כי לא ירד במדרגה אחת לפחות
93 זה תקין כי יש ירדה במדרגת אחת (שים לב בתנאים שנבדקו עכשיו גם הבדיקה הזו היתה יוצאת לא תקינה כי זה לא כפולות של המדרגה).

**Comment by assafmodi** [comment]
בוצע!

**Comment by KerenMe** [comment]
קיימים שלושה פרמטרים
prevprice: המחיר הקודם המוחזר מהשרת
price:  המחיר הנוכחי
step: מדרגת המחיר

senario 1:
בעליית הדף המחיר המוצג הינו 
PRICE ולידו מדרגת המחיר המוצעת
בעת שינוי ידני של המחיר הבדיקה הינה:
Diff = (prevprice-price).ABSOLUTE()
newPrice = Diff - step
if(newPrice <0){ יש להציג הודעת שגיאה  : "לא ירדת בלפחות מדרגת מחיר {step}"}

senario 2: 
במידה וה prevprice הינו NULL
אזי הבדיקה היא תהיה מול ה price

**Comment by assafmodi** [comment]
בוצע
