### ISSUE TITLE
דף מכרז רגיל - הצגת יחידות רלוונטי ליד שדות כמות

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#5]
בעליית דף מכרז נעשת קריאה לפונקציה שמחזירה את השדה AmountSign
יש להשתמש בערך בשדה זה בכל מקום שבו מציג כמות
כאשר זה יחידות זה מגיע ריק
רלוונטי בעיקר כשמדובר במכרז עם כמויות שהם אחוזים

**Comment by KerenMe** [comment]
קריאה לפונקציה TenderAndCurrentPropositionLines

**Comment by assafmodi** [comment]
אם הערך בשדה ה amountSign ריק הליבל של השדה הוא מספר יחידות אם רשום אחוזים אז הליבל הוא משקל

**Comment by assafmodi** [comment]
בוצע

![image](https://user-images.githubusercontent.com/86707714/153015002-ef7ee62e-d49b-4b09-a7b6-33fc60038c7d.png)
