### ISSUE TITLE
דף מכרז - הודעות קבועות קופצות

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#52]
1. כאשר מסמנים את ה CHECK BOX של "אל תציג שוב" לאחר פתיחת המכרז שוב עדין מוצגות ההודעות
2. משום מה למרות שיש הודעה אחת בדיאלוג מוצגים שתי הודעות

**Comment by assafmodi** [comment]
נסגר וטופל ע"י קרן
