### ISSUE TITLE
דף מכרז רגיל - מכרז משקל באחוזים

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#6]
בעליית דף המכרז נעשת קריאה לשרת ומתקבל ערך בשדה IsPercentageCalculation אם הערך הוא TRUEאזי זהו מכרז  משקל באחוזים
בשדה יחידות צריך שיהיה רשום "משקל"ולא "יחידות"
בעת חישוב סה"כ לכל פריט יש לחשב מחיר כפול כמות לחלק ל 100

**Comment by KerenMe** [comment]
קריאה לפונקציה TenderAndCurrentPropositionLines

**Comment by assafmodi** [comment]
בוצע

const CalculateLineTotal = (tender : TenderDto, tenderLine: TenderLineDto) => {
  return tender.IsPercentageCalculation ? 
    tenderLine.Price * tenderLine.RequiredAmount / 100 :
    tenderLine.Price * tenderLine.RequiredAmount;
}
