### ISSUE TITLE
מכרז עם העדפות - אזור פריט במכרז

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#69]
יש לבנות קומפוננטה חדשה לאזור הפריט של מכרז עם העדפות 
זהו בעצם הקומפוננטה שתחליף את TenderLines - נקרא לה TenderWithBenfitLine
סקיצה של הקומפוננטה ניתן לראות בעיצוב החדש

**Comment by assafmodi** [comment]
בוצע
