### ISSUE TITLE
מכרז עם העדפות גודל פונט

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#73]
יש לוודא שכל הגדלים מוגדרים ב PT ולא ב EM
יש לוודא שכל הגדלים מוגדרים כפי שהוגדר באפיון

**Comment by assafmodi** [comment]
בוצע
שוב...עם פרופורציות לגודל המסך

**Comment by assafmodi** [comment]
עבדתי עם הכלי הזה:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/86707714/187630512-5ed6514a-6944-4d2c-a5d1-b3e8f6d66492.png">
