### ISSUE TITLE
מכרז עם העדפות - תחשיב אחוז מרכיב עבודה ומרכיב תוצרת הארץ

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#75]
משמאל לשדה מרכיב כוח אדם יש להציג את האחוז
משמאל לשדה מרכיב תוצרת הארץ יש להציג את האחוז

אחוז כוח עבודה
באם יש ערך בשדה מחיר ליחידה ויש ערך בשדה עלות מרכיב כוח אדם יש לעשות את התחשיב
מרכיב כוח אדם יקרא א
מחיר ליחידה  יקרא ב

אחוז מרכיב תוצרת הארץ
באם יש ערך בשדה מחיר ליחידה ויש ערך בשדה מרכיב תוצרת הארץ יש לעשות את התחשיב
מרכיב תוצרת הארץ יקרא א
מחיר ליחידה  יקרא ב

התחשיב בשני המקרים הוא:
א לחלק ל ב כפול 100

**Comment by assafmodi** [comment]
כמה ספרות אחרי הנקודה צריך?

**Comment by assafmodi** [comment]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/86707714/186404819-ee788d26-76f6-441e-8c27-11056aef407f.png">

**Comment by KerenMe** [comment]
להציג 2 ספרות
בכל התחשיבים צריך לשמור 6 ספרות.
לדאוג שאתה לא מעגל למעלה לפני הצגה אלא רק למטה
כלומר 12.346 יוצג 12.34 ולא 12.35

בתאריך יום ד׳, 24 באוג׳ 2022, 14:01, מאת assaf biton ‏<
***@***.***>:
