### ISSUE TITLE
מכרז עם העדפות - שדה מרכיב תוצרת הארץ

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#76]
אם הערך המוזן בשדה זה גדול מהערך המוזן במחיר ליחידה יש להציג את ההודעה
הערך בשדה מרכיב תוצרת הארץ צריך להיות קטן או שווה למחיר ליחידה

אם הערך המוזן בשדה זה קטן מאפס יש להציג את ההודעה המוצגת כאשר מנסים לשים בשדה מחיר ליחדה ערך קטן מאפס

הולידציות והודעות השגיאה צריכות להיות מוצגות כפי שמוצגות בשדה מחיר ליחידה

**Comment by assafmodi** [comment]
בוצע

<img width="807" alt="image" src="https://user-images.githubusercontent.com/86707714/187392144-1abc857b-c694-479b-92ae-2f2fbef9b7e8.png">

**Comment by KerenMe** [comment]
במידה ויש הודעת שגיאה אין לעשות תחשיב של האחוזים

**Comment by assafmodi** [comment]
else {
          line.MadeInIsraelPercent = action.payload.Price ? (Number(action.payload.value) / action.payload.Price) * 100 : 0;
          TenderWithBenfitLineTotals(state.Tender, state);
        }

בוצע
