### ISSUE TITLE
מכרז עם העדפות - תצוגה למי שאין העדפה

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#78]
בפתיחת דף מכרז כאשר הערך בשדה BenefitType הוא ריק המשמעות היא שהספק המחובר למערכת הוא ללא העדפות
במקרה זה יש להסיר מהמסך את:
שדה מרכיב עבודה
שדה מחושב אחוז מרכיב עבודה
שדה מחושב סה"כ בניכוי העדפה לאומית
שדה מרכיב תוצרת הארץ
שדה מחושב אחוז מרכיב תוצרת הארץ
שדה מחושב סה"כ בניכוי תוצרת הארץ

**Comment by assafmodi** [comment]
בוצע
