### ISSUE TITLE
מכרז עם העדפות - תצוגה לבעל העדפה AreaAWithoutMadeInIsrael או ConfrontationLineWithoutMadeInIsrael

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#79]
בפתיחת דף מכרז כאשר הערך בשדה BenefitType הוא AreaAWithoutMadeInIsrael או ConfrontationLineWithoutMadeInIsrael
במקרה זה יש להסיר מהמסך את:
שדה מחושב סה"כ בניכוי תוצרת הארץ

**Comment by assafmodi** [comment]
הסרתי גם את השדה וגם את החישוב למטה  בניכוי תוצרת הארץ....

**Comment by KerenMe** [comment]
אני חושבת שבבאג רשמתי רק להוריד את החישוב למטה נכון?
זה מה שצריך להיות. השדה כן חשוב רק התחשיב לא רלוונטי

קרן

בתאריך יום א׳, 28 באוג׳ 2022, 11:31, מאת assaf biton ‏<
***@***.***>:
