### ISSUE TITLE
דף מכרז רגיל

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#8]
בכל מקום בדף המכרז יש להציג מספריםע ם 2 נקודות אחרי הנקודה ועם פסיקים של אלפים ומיליונים
1,000,000.00

**Comment by assafmodi** [comment]
![image](https://user-images.githubusercontent.com/86707714/153007056-1099a598-1068-427f-9f7b-0f6084fdae01.png)

הוכנסה הפונקציה של חישוב מחיר לעיל בכל המקומות בהם צריך
