### ISSUE TITLE
מכרז עם העדפות - תצוגה לספק עם עדיפות MadeInIsrael

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#80]
בפתיחת דף מכרז כאשר הערך בשדה BenefitType הוא MadeInIsrael
במקרה זה יש להסיר מהמסך את:
שדה מרכיב עבודה
שדה מחושב אחוז מרכיב עבודה
שדה מחושב סה"כ בניכוי העדפה לאומית

**Comment by assafmodi** [comment]
בוצע
   {item.BenefitType || item.BenefitType !=="MadeInIsrael" &&
