### ISSUE TITLE
מכרז עם העדפות - שדה סה"כ בניכוי העדפה לאומית

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#81]
כאשר יש שינוי בשדות מחיר ליחידה, מרכיב תוצרת הארץ או מרכיב עבודה יש לשנות גם את השדות סה"כ בניכוי העדפת תוצרת הארץ וסה"כ בניכוי העדפת לאומית.

כרגע התחשיב לא חשוב מבקשת רק שיהיה EVENT שישנה את המחיר

**Comment by assafmodi** [comment]
סה"כ הצעה משתנה כאשר משנים מחיר ליחידה
סה"כ בניכוי תוצרת הארץ משתנה כאשר משנים מחיר ליחידה או מרכיב תוצרת הארץ
סה"כ בניכוי העדפה לאומית משתנה כאשר משנים מחיר ליחידה אן מרכיב כוח עבודה.

**Comment by assafmodi** [comment]
משתשש פה במרכיבים הבאים : 

הכרזה על משתנים ופונקציות שניתנות לאיתחול

  const [calcPrice, setCalcPrice] = useState<number>(0);
  const [calcWorkForce, setCalcWorkForce] = useState<number>(0);
  const [calcMadeInCountry, setCalcMadeInCountry] = useState<number>(0);

כרגע מאתחל אותם עם ערכים שאת מחזירה
    setCalcPrice(itemx.TotalWithoutBenefits);
    setCalcWorkForce(itemx.TotalForLocalWork);
    setCalcMadeInCountry(itemx.TotalWithLocationBenefit);

מציג אותם בערכים בדף למטה ך:
{workForceCondition &&
                            <Grid item justifyContent="center" className={Styles.item}>
                              <Grid item justifyContent="center" className={Styles.title}>בניכוי העדפה לאומית</Grid>
                              <Grid item justifyContent="center" className={Styles.summery}><CurrencyFormat displayType={'text'} thousandSeparator={true} decimalScale={2} />
                                **{calcMadeInCountry}**&nbsp;</Grid>
                            </Grid>
                          }

                          {madeInCountryCondition &&
                            <Grid item justifyContent="center" className={Styles.item}>
                              <Grid item justifyContent="center" className={Styles.title}>בניכוי תוצרת הארץ</Grid>
                              <Grid item justifyContent="center" className={Styles.summery}><CurrencyFormat displayType={'text'} thousandSeparator={true} decimalScale={2} />
                                **{calcWorkForce}**&nbsp;</Grid>
                            </Grid>
                          }
                          <Grid item justifyContent="center" className={Styles.item}>
                            <Grid item justifyContent="center" className={Styles.title}>{Translation('Tender.THE_AMOUNT_OF_YOUR_BID')}</Grid>
                            <Grid item justifyContent="center" className={Styles.summery}><CurrencyFormat displayType={'text'} thousandSeparator={true} decimalScale={2} />
                              **{calcPrice}**</Grid>
                          </Grid>
