### ISSUE TITLE
דף מכרז רגיל - רשימת פריטים

### ISSUE THREAD

**Issue by KerenMe** [MODMLN/Mod.DynTender#9]
בעת עליית המכרז נעשת קריאה לפונקציה ובה מקבלים רשימה של LINES
לכל פריט צריך להשתמש בערכים מהשדות
"RequiredAmount":100.00,
"Price":700.00,
"TenderLineId":28,
"TenderLineName":"פריט 1",
"PriceStep":5.00,
"TotalPriceForDisplay":70000,
"Index":1,

**Comment by KerenMe** [comment]
קריאה לפונקציה TenderAndCurrentPropositionLines

**Comment by KerenMe** [comment]
בפריט יש יכולת רק לראות את הנתונים ואז באותה שורה רואים את שם הפריט היחידות  המחיר ליחידה והסה"כ
יש אפשרות להרחיב את השורה ואז הנתונים של  מחיר ליחידה וסה"כ יורדים לשורה מתחת
בשלב הזה ניתן לשנות את המחיר ליחידה

**Comment by assafmodi** [comment]
בוצע
